### ISSUE TITLE
Excellibrary Installation failing

### ISSUE THREAD

**Issue by revathikanakachalam** [ravihuang/robotframework-excellibrary#1]
I am trying to install excel library using command "pip install robotframework-excellibrary", installation is failing with below error

```
C:\Users\SESA672171>pip install robotframework-excellibrary
Collecting robotframework-excellibrary
  Using cached robotframework-excellibrary-0.0.2.zip (61 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\SESA672171\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\SESA672171\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\SESA672171\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\SESA672171\AppData\Local\Temp\pip-build-env-ruf9qzhx\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\SESA672171\AppData\Local\Temp\pip-build-env-ruf9qzhx\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\SESA672171\AppData\Local\Temp\pip-build-env-ruf9qzhx\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\SESA672171\AppData\Local\Temp\pip-build-env-ruf9qzhx\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
      NameError: name 'execfile' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I am using below version of python and robot
Python 3.10.11
Robot Framework 6.1.1 (Python 3.10.11 on win32)

**Comment by dxtr80** [comment]
I got the same output with this package (works ok with py2.7) on Python 3.11.3 64bit and robotframework 7.1. 
@revathikanakachalam Please check. I'm now testing another package https://github.com/zero88/robotframework-excel
